project:
  type: website
  output-dir: docs

website:
  title: "profrobson"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/robsonfvilela
      - icon: twitter
        href: https://twitter.com/robsonfvilela
format:
  html:
    theme: solar
    css: styles.css



